# Installer container for building bootc-installer ISOs
# This container includes Anaconda and required tools for ISO creation
FROM quay.io/fedora/fedora-bootc:latest@sha256:8cd9b0ff82fe1c18413dcb5efe74e4ce2bbd18365c1ad006488d76fd05c89b62

RUN --mount=type=cache,target=/var/cache \
    --mount=type=cache,target=/var/lib \
    --mount=type=cache,target=/var/log \
    --mount=type=cache,target=/var/tmp \
    --mount=type=tmpfs,target=/tmp \
    dnf install -y \
    anaconda \
    anaconda-install-env-deps \
    anaconda-dracut \
    dracut-config-generic \
    dracut-network \
    net-tools \
    squashfs-tools \
    grub2-efi-x64-cdboot \
    python3-mako \
    lorax-templates-generic \
    biosdevname \
    prefixdevname

# Fedora 43+ moved the shim and grub2 EFI binaries from /boot to /usr/lib/efi
# (see https://fedoraproject.org/wiki/Changes/BootLoaderUpdatesPhase1). osbuild's
# installer ISO stage still reads /boot/efi/EFI/fedora, so copy the binaries back
# into place. On Fedora 42 the fix was `dnf reinstall shim-x64`, which no longer
# works. See https://osbuild.org/docs/bootc/
RUN mkdir -p /boot/efi && cp -ra /usr/lib/efi/*/*/EFI /boot/efi

# lorax wants to create a symlink in /mnt which points to /var/mnt
# on bootc but /var/mnt does not exist on some images
RUN mkdir -p /var/mnt
